### ISSUE TITLE
Return tag and $this

### ISSUE THREAD

**Issue by Swader** [dotink/sage#3]
Return tag breaks when returning `$this`. In most IDEs and other doc generators, a return of `$this` automatically implies the current class. IMO, Sage should support this. Many projects have `$this` in return tags.

**Comment by mattsah** [comment]
To be clear, the format that is most common is just:

```
@return $this
```

With no descripton or type?

**Comment by Swader** [comment]
Not most common, but common enough. Yes, like this. Type is automatically inferred from the current class, and replaces `$this` during documentation generation. Description is, in those cases, not necessary, because the classes themselves are documented.

**Comment by mattsah** [comment]
Let me know if 1.0.3 / a0e264c18931d3734decf9a93cd321ab506298f7 looks right.
