### ISSUE TITLE
@throws

### ISSUE THREAD

**Issue by Swader** [dotink/sage#4]
Similar to the `@returns` problem, `@throws` should be followed by type, and then an *optional* description.

[Info](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/throws.html).

I keep posting these as I run into them, basically trying it out live on [this](https://github.com/Swader/diffbot-php-client).

**Comment by mattsah** [comment]
Should be solved in 1.0.4 / fb387454f0d6e1bbbf319d0f99a900ab9d3eecc3

Definitely welcome any more of these, but I do need to go to bed (it's rather late here).  That said, a quick examination of your docblocks looks like you may see some other strange output.  Sage will generally ignore token it doesn't understand, but it's strict on ones it does.  There's also some catches to the formatting, for example, right now I'm not sure it support multi-line descriptions as shown in the info you linked to.  I would definitely consider these all bugs, so feel free to keep opening issues, but I may not be able to close them until later in the day tomorrow.

As for new features such as prose or different/extended/cleaned up templating (right now it's markdown mixed with some HTML, but it's pretty much only tested on github), I welcome those too, but they'd obviously take longer.  The existing markdown templates and api docs should give a pretty good idea how to generate other templates with PHP, although at the moment template directory is hard coded in the bin/sage script.

If you're looking to write your own templates in RST best bet might be just to move the current set into a subfolder called github or something, and copy then modify.

Also, Sage definitely doesn't have all the token support it should.  But in the sage.config you can register your own tokens such as 'name' => 'Some\Token\Parsing\Class', it just needs to implement validate and parse, whatever parse returns is accessible directly in templates which should also show how to get the data.

**Comment by Swader** [comment]
Sounds good, looking forward to playing around with it all. No rush on upgrades, I'll do what I can on my end, too.
